"use client"; // This component uses browser features like file input and state

import {
  ImageKitAbortError,
  ImageKitInvalidRequestError,
  ImageKitServerError,
  ImageKitUploadNetworkError,
  upload,
} from "@imagekit/next";
import { useState } from "react";

// Props accepted by this component
interface FileUploadProps {
  // Function called after a successful upload
  onSuccess: (res: any) => void;

  // Optional callback to send upload progress
  onProgress?: (progress: number) => void;

  // Determines whether only image or video files are accepted
  fileType?: "image" | "video";
}

const FileUpload = ({ onSuccess, onProgress, fileType }: FileUploadProps) => {
  // Tracks whether a file is currently uploading
  const [uploading, setUploading] = useState(false);

  // Stores any validation or upload error
  const [error, setError] = useState<string | null>(null);

  // Validate the selected file before uploading
  const validateFile = (file: File) => {
    // If uploading a video, ensure the selected file is a video
    if (fileType === "video") {
      if (!file.type.startsWith("video/")) {
        setError("Please upload a valid video file");
      }
    }

    // Limit the maximum file size to 100 MB
    if (file.size > 100 * 1024 * 1024) {
      setError("File size must be less than 100 MB");
    }

    return true;
  };

  // Runs whenever the user selects a file
  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    // Get the first selected file
    const file = e.target.files?.[0];

    // Stop if no file is selected or validation fails
    if (!file || !validateFile(file)) return;

    setUploading(true);
    setError(null);

    try {
      // Fetch authentication parameters from our backend.
      // These are required for secure uploads to ImageKit.
      const authRes = await fetch("/api/auth/imagekit-auth");
      const auth = await authRes.json();

      // Upload the file directly to ImageKit
      const res = await upload({
        // File to upload
        file,

        // Original filename
        fileName: file.name,

        // Public ImageKit key
        publicKey: process.env.NEXT_PUBLIC_PUBLIC_KEY!,

        // Authentication values generated by the server
        signature: auth.signature,
        expire: auth.expire,
        token: auth.token,

        // Called repeatedly while the upload is in progress
        onProgress: (event) => {
          // lengthComputable tells us whether the browser
          // knows the total upload size.
          if (event.lengthComputable && onProgress) {
            // Calculate upload percentage
            const percent = (event.loaded / event.total) * 100;

            // Send the percentage back to the parent component
            onProgress(Math.round(percent));
          }
        },
      });

      // Notify the parent component that upload succeeded
      onSuccess(res);
    } catch (error) {
      // Handle upload errors
      console.error("Upload failed", error);
    } finally {
      // Stop showing the loading state
      setUploading(false);
    }
  };

  return (
    <>
      <input
        // File picker
        type="file"
        // Restrict selectable file types
        accept={fileType === "video" ? "video/*" : "image/*"}
        // Trigger upload when a file is selected
        onChange={handleFileChange}
      />

      {/* Display while uploading */}
      {uploading && <span>Loading....</span>}
    </>
  );
};

export default FileUpload;
